### ISSUE TITLE
PartnerBillingKey error

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#15]
I used the API key and submitted in Payment object as PartnerBillingKey.

I get back:
{u'HadError': True, u'Errors': [{u'PropertyName': u'Partner Billing Key', u'ErrorMessage': u'Invalid key', u'AttemptedValue': None, u'CustomState': None}], u'ErrorReferenceCode': u'0274071b-c167-48ca-b920-a117dfbde16c'}

Added Total value but same error. Does it give that error if the total amount is not correct?

**Comment by micahasmith** [comment]
It means your partner billing key is incorrect. Can you paste in an example of what your POSTing (except with a diff private key, of course)

**Comment by AustenB** [comment]
Chris - I just emailed you your live billing key to confirm
 you are using the right one

On Thu, Mar 12, 2015 at 2:50 PM, Micah Smith notifications@github.com
wrote:

> It means your partner billing key is incorrect. Can you paste in an
> example of what your POSTing (except with a diff private key, of course)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/15#issuecomment-78565266
> .

## 

Austen Bernstein
Founder & CEO
printio

**Comment by chrischen** [comment]
Payment": {
  "PartnerBillingKey": "1B4/TVurRc+PZbHjrirBjienE5B84Gke2GzOr1=", # fake dev key
  "Total": 12.5
}

**Comment by chrischen** [comment]
Sorry, the issue was for some reason I was testing the calls on the production endpoint.

Do I have to send the exact Total amount of the order? What if your prices change?

**Comment by micahasmith** [comment]
orders on credit do not need amount passed
