### ISSUE TITLE
Will Items in GET /order ever return multiple SKUs?

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#16]
Will same SKU items always be shipped together with one tracking number?

Is it possible to have the same SKU be returned multiple times with different tracking numbers?

**Comment by chrischen** [comment]
Will the same Sku only show up once in Items?

```
"Items": [
    {
      "Sku": "string",
      "ProductId": "integer",
      "Product": "string",
      "Quantity": "integer",
      "Status": "string",
      "TrackingNumber": "string",
      "TrackingUrl": "string",
      "ShipCarrierName": "string",
      "Price": {...},
      "DiscountAmount": {...},
      "SourceId": "string"
    }
  ]
```

**Comment by micahasmith** [comment]
Same sku'd items will the majority of the time be shipped together.

After a certain quantity of items, however, multiple tracking numbers will be employed.

**Comment by chrischen** [comment]
If multiple tracking numbers for the same SKU are employed, how do I distinguish which tracking number is for which image ordered?

**Comment by micahasmith** [comment]
@chrischen i can't think of a scenario where a tracking number indicates a different image within the same orderitem. in other words, a single orderitem is never split

**Comment by chrischen** [comment]
```
"Items": [
    {
      "Sku": "sku1", // IMAGE 1
      "ProductId": "integer",
      "Product": "string",
      "Quantity": "integer",
      "Status": "string",
      "TrackingNumber": "string",
      "TrackingUrl": "string",
      "ShipCarrierName": "string",
      "Price": {...},
      "DiscountAmount": {...},
      "SourceId": "string"
    },
    {
      "Sku": "sku1", // IMAGE 2
      "ProductId": "integer",
      "Product": "string",
      "Quantity": "integer",
      "Status": "string",
      "TrackingNumber": "string",
      "TrackingUrl": "string",
      "ShipCarrierName": "string",
      "Price": {...},
      "DiscountAmount": {...},
      "SourceId": "string"
    }
  ]
```

How do I tell which which tracking number is for which image, if the SKUs are the same, or are you saying the same SKU is never split?

**Comment by micahasmith** [comment]
A sku can have multiple images under it. For instance, a photobook can have 60 images.

If you want to track items, you can provide a `SourceId` to identify them via your own ID.

**Comment by chrischen** [comment]
A photo book will return 60 items, each with tracking number and price?

**Comment by micahasmith** [comment]
A photo book will return one item. 

I think it would be beneficial for you to submit some orders on staging-- it'll give you a full glimpse into what orders GET and POST both do and return.

**Comment by micahasmith** [comment]
To be extra explicit, item != image. 

An item can have many images. It's a 1 to many relationship.

**Comment by chrischen** [comment]
I submitted orders to the staging but there was no way to move the status forward.

Ok so in the Items array above, an SKU can show up multiple times (referring to different physical items), but each piece ordered (say canvas print) will show up once in the Items list above (even if they have the same tracking number)?

The Price field corresponds to the cost of that item, and then the ShippingTotal is the total shipping cost. But is there a way to get back the shipping cost of each tracking number?

**Comment by micahasmith** [comment]
Yes they will show up once even if they have the same tracking number (if they were consolidated into one box). 

Shipping is per consolidation.

**Comment by chrischen** [comment]
So is there way to break the shipping cost down by each box (tracking number)? This is for our accounting purposes.
