### ISSUE TITLE
Updating status in staging admin panel

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#18]
How do I change the status of test orders in the staging admin panel so I can get back various statuses for orders from the API?

**Comment by bhox** [comment]
Hi Chris, you can use our staging site to view staging orders: https://staging-admin-v2.print.io

**Comment by chrischen** [comment]
Yee but how do I change the order statuses?

**Comment by bhox** [comment]
You can go to the orders listing, click on an  order, click to the 'status' tab. Select items in the order and pick the new status and a comment on the top to change statuses. Shoot me an email and we can hop on the phone if it's confusing.

**Comment by chrischen** [comment]
It only shows Hold and Canceled.

**Comment by bhox** [comment]
@chrischen yes, the other statuses are used & set by our backend services and are not manually editable

**Comment by chrischen** [comment]
So how do I test status changes in the api?

**Comment by bhox** [comment]
What are you testing? Display of orders? I can move some orders to another status if you'd like.

**Comment by chrischen** [comment]
I am getting status of orders through the API. So I just need some orders to progress through the normal status flow.

**Comment by bhox** [comment]
@chrischen I've updated your two orders to two statuses: one is Needs Manual Approval, which is a status that means someone on our side will approve the item before it gets printed (you can turn this off if you're confident in your images). The other is 'Delivered' which is where orders land when they've been produced and delivered.

**Comment by chrischen** [comment]
Can you set the manual approval to in produce tion?

**Comment by bhox** [comment]
Updated order 111100 to InProduction

**Comment by chrischen** [comment]
I've also been waiting on answers to these two blocking questions:

https://github.com/printdotio/printio-api/issues/17
https://github.com/printdotio/printio-api/issues/16

Thanks
