### ISSUE TITLE
Use Braintree Payment Nonce to Submit order

### ISSUE THREAD

**Issue by barnbucket** [printdotio/printio-api#19]
To submit an order the API is requires Braintree's encrypted Credit Card#, CCV, and EXP date. 

Instead of passing those fields we would like to submit an order with just the payment method nonce generated from the Braintree SDK. This should take the place of the above fields.

**Comment by jmselk** [comment]
This looks right to me. Since the Braintree SDK flow hides the encrypted CC #, Expiration and CVV codes and just hands off the nonce, we'll have no other way of submitting the order.

**Comment by micahasmith** [comment]
on staging

**Comment by ngilas** [comment]
I assume you placed a new field on the order for the payment nonce... Is it the "PartnerBillingKey" in the payment section? Also, are the other values in the payment object optional since all of the info is contained within the nonce?

**Comment by micahasmith** [comment]
`Payment.BraintreeEncryptedNonce`

https://staging-api.print.io/docs/#!/orders/POST_post_1

You only need to also pass `Total`
