### ISSUE TITLE
Followup question to issue 16

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#20]
Not sure if it notifies you on closed issues, but i have a followup question to https://github.com/printdotio/printio-api/issues/16 at the bottom, as well as on #17 https://github.com/printdotio/printio-api/issues/17.

**Comment by austincprintio** [comment]
@micahasmith Please see above issue regarding original issue #16 as well as #17. Thanks!

**Comment by micahasmith** [comment]
@austincprintio done.
