### ISSUE TITLE
Problems with Shipping Prices

### ISSUE THREAD

**Issue by dafinley** [printdotio/printio-api#21]
I created a jsfiddle trying to get shipping prices for the canvas wrap. But it is not returning a price for the items...It works for other items, but we definitely would not want to have a zero shipping being added for an order like 5 canvas wraps.  Any clues - http://jsfiddle.net/starlineventures/dxn3w3e8/

**Comment by AustenB** [comment]
It works just fine for your recipe. The response is below.

For testing the API use:

api.print.io/docs

It will always give you the correct API results.

Input:

{
  "ShipToPostalCode": "70130",
  "ShipToCountry": "US",
  "ShipToState": "LA",
  "CurrencyCode": "USD",
  "LanguageCode": "en",
  "Items": [
    {
      "SKU": "CanvsWrp-WhtWrp-32x48",
      "Quantity": "5"
    }
  ]
}

Output:

{ "Result": [ { "SKUs": [ "CanvsWrp-WhtWrp-32x48" ], "ShipOptions": [ { "
CarrierName": "Standard", "MethodType": "Standard", "Name": "Standard", "
Price": { "Price": 90, "CurrencyCode": "USD", "FormattedPrice": "$90.00", "
CurrencyFormat": "${1}", "CurrencyDigits": 2 }, "Id": 1, "
EstBusinessDaysTilDelivery": 12, "MethodId": 3 }, { "CarrierName":
"Expedited", "MethodType": "Expedited", "Name": "Expedited", "Price": { "
Price": 215, "CurrencyCode": "USD", "FormattedPrice": "$215.00", "
CurrencyFormat": "${1}", "CurrencyDigits": 2 }, "Id": 2, "
EstBusinessDaysTilDelivery": 4, "MethodId": 5 }, { "CarrierName":
"Overnight", "MethodType": "Overnight", "Name": "Overnight", "Price": { "
Price": 319.75, "CurrencyCode": "USD", "FormattedPrice": "$319.75", "
CurrencyFormat": "${1}", "CurrencyDigits": 2 }, "Id": 3, "
EstBusinessDaysTilDelivery": 2, "MethodId": 7 } ] } ] }

On Wed, Apr 8, 2015 at 11:15 PM, Starline Ventures <notifications@github.com

> wrote:
> 
> I created a jsfiddle trying to get shipping prices for the canvas wrap.
> But it is not returning a price for the items...It works for other items,
> but we definitely would not want to have a zero shipping being added for an
> order like 5 canvas wraps. Any clues -
> http://jsfiddle.net/starlineventures/dxn3w3e8/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/21.

## 

Austen Bernstein
Founder & CEO
printio

**Comment by dafinley** [comment]
Strange man...my object is empty?
![screenshot 2015-04-09 at 4 54 28 am](https://cloud.githubusercontent.com/assets/441184/7063440/9ef3cd52-de74-11e4-8ee7-338a2c205fbe.png)

**Comment by dafinley** [comment]
You'll see the ShipOptions: Array[0] is an empty array.  The __proto stuff is just helper functions and variables

**Comment by vsergi23** [comment]
all is there @dafinley 
https://api.print.io/docs/#!/shippingprices/Get_post_0
![screenshot 2015-04-09 12 05 25](https://cloud.githubusercontent.com/assets/7405464/7063691/80103aaa-deb1-11e4-8da4-4f57b1e183a9.png)
![screenshot 2015-04-09 12 05 32](https://cloud.githubusercontent.com/assets/7405464/7063693/81a89b5a-deb1-11e4-82c6-779dbd28a1cc.png)
![screenshot 2015-04-09 12 05 49](https://cloud.githubusercontent.com/assets/7405464/7063697/837b7ce0-deb1-11e4-87d8-66bcfd01bc05.png)
![screenshot 2015-04-09 12 05 56](https://cloud.githubusercontent.com/assets/7405464/7063702/850ce864-deb1-11e4-841e-09bd7030f0ef.png)
![screenshot 2015-04-09 12 10 18](https://cloud.githubusercontent.com/assets/7405464/7063707/86a1dd4c-deb1-11e4-84f3-4afa21031286.png)

**Comment by dafinley** [comment]
Strange man...I do not see what you see??
![screenshot 2015-04-09 at 5 17 33 am](https://cloud.githubusercontent.com/assets/441184/7063818/c711ed02-de77-11e4-9e39-107cfddf05bb.png)
![screenshot 2015-04-09 at 5 17 21 am](https://cloud.githubusercontent.com/assets/441184/7063817/c70f7d2e-de77-11e4-859e-d99b02aa440b.png)

**Comment by vsergi23** [comment]
@dafinley country code should be 2 symbols -- **US** instead of **_USA**_

**Comment by dafinley** [comment]
Whenever I swap out a new SKU...it works as expected but the Canvas wrap sku is giving me blank objects in return
![screenshot 2015-04-09 at 5 21 01 am](https://cloud.githubusercontent.com/assets/441184/7063875/69debd12-de78-11e4-8ea2-85fbf40d4e69.png)
![screenshot 2015-04-09 at 5 20 29 am](https://cloud.githubusercontent.com/assets/441184/7063874/69dca95a-de78-11e4-9595-ad79aba05c41.png)

**Comment by dafinley** [comment]
Changing the Country Code Worked!!...It threw me off because it always returned a good response up until then.

**Comment by dafinley** [comment]
I updated the JSFiddle to point to address in Rio de Janeiro, but I am unable to get a shipping price.  All the relevant data is contained in the JS Fiddle including the link to the google maps address...it is the address of a hotel.  Can you guys help?  http://jsfiddle.net/starlineventures/dxn3w3e8/

**Comment by AustenB** [comment]
What product -> some products don't ship to Brazil due to customs, inport
taxes and fees. Etc.

We will be adding more manufacturers in Brazil to avoid this issue.

On Mon, Apr 13, 2015 at 7:45 PM, Starline Ventures <notifications@github.com

> wrote:
> 
> I updated the JSFiddle to point to address in Rio de Janeiro, but I am
> unable to get a shipping price. All the relevant data is contained in the
> JS Fiddle including the link to the google maps address...it is the address
> of a hotel. Can you guys help?
> http://jsfiddle.net/starlineventures/dxn3w3e8/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/21#issuecomment-92537876
> .

## 

Austen Bernstein
Founder & CEO
printio

**Comment by dafinley** [comment]
Ahhh...these are canvas wraps.  Do you think Europe has more coverage?

**Comment by AustenB** [comment]
Yes it definitely does. What size are you using.

For Canvas (use the 12x12 inch ones) to test where they are available.

so the same sku - just use 12x12 (since the 32x48 might not be a normal
size ordered internationally.)

On Mon, Apr 13, 2015 at 7:49 PM, Starline Ventures <notifications@github.com

> wrote:
> 
> Ahhh...these are canvas wraps. Do you think Europe has more coverage?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/21#issuecomment-92538746
> .

## 

Austen Bernstein
Founder & CEO
printio

**Comment by dafinley** [comment]
Much appreciated....It does not look like the state code matters outside of the US...it seems like as long as the Postal Code matches the Country Code...we will get a result that comes back in a price based off the currency code sent. 
![screenshot 2015-04-13 at 8 05 21 pm](https://cloud.githubusercontent.com/assets/441184/7127887/93856802-e218-11e4-9724-c43dc5555e96.png)

**Comment by dafinley** [comment]
For some reason, I'm still having more issues with the Shipping Price API.
The price to ship a single throw pillow is coming back as $26.31???  When it should be more like $11
![screenshot 2015-04-22 at 12 24 16 am](https://cloud.githubusercontent.com/assets/441184/7267773/f3e65062-e885-11e4-8b9c-af39d2c65cd7.png)

![screenshot 2015-04-22 at 12 20 14 am](https://cloud.githubusercontent.com/assets/441184/7267767/da8d5e76-e885-11e4-9389-b8b912b8db7a.png)

**Comment by dafinley** [comment]
The shipping speed image is using the Backend order form...the pink api result is using the same address but coming back with a wrong shipping price??.  
'{
  "ShipToPostalCode": "70458",
  "ShipToCountry": "USA",
  "ShipToState": "LA",
  "CurrencyCode": "USD",
  "LanguageCode": "EN",
  "Items": [
    {
      "SKU": "ThrowPillow_Sewn_16x16",
      "Quantity": "4"
    }
  ]
};'

**Comment by dafinley** [comment]
Should be one...the price that is coming back for $26 is using a single pillow as an example...not 4.
{
  "ShipToPostalCode": "70458",
  "ShipToCountry": "USA",
  "ShipToState": "LA",
  "CurrencyCode": "USD",
  "LanguageCode": "EN",
  "Items": [
    {
      "SKU": "ThrowPillow_Sewn_16x16",
      "Quantity": "1"
    }
  ]
};

**Comment by micahasmith** [comment]
weird. going to forward to our data team

**Comment by dafinley** [comment]
Thanks!!

**Comment by AustenB** [comment]
You must use country code US - not USA.

I apologize for our documentation. It should state this specifically

On Wed, Apr 22, 2015 at 1:26 AM, Starline Ventures <notifications@github.com

> wrote:
> 
> Should be one...the price that is coming back for $26 is using a single
> pillow as an example...not 4.
> {
> "ShipToPostalCode": "70458",
> "ShipToCountry": "USA",
> "ShipToState": "LA",
> "CurrencyCode": "USD",
> "LanguageCode": "EN",
> "Items": [
> {
> "SKU": "ThrowPillow_Sewn_16x16",
> "Quantity": "1"
> }
> ]
> };
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/21#issuecomment-95039080
> .

## 

Austen Bernstein
Founder & CEO
printio

**Comment by dafinley** [comment]
Nope that was my fault. You guys told me that ALREADY!!  I think I was using old code.  Thanks for clearing this up so quick.

**Comment by AustenB** [comment]
@dafinley no problem. Closing issue. 

We will update the docs for the Shipping Section specifically to make sure people dont use 3 digit country codes and will update error references for such.
