### ISSUE TITLE
Need explanation for paramters get_product_list

### ISSUE THREAD

**Issue by djeet** [printdotio/printio-api#23]
Trying to integrate the API into Woo Commerce and need help with explanation of few parameters.

Here is the reference link:http://www.bakingcode.org/print_io/?function=6&submit=Submit

All questions w.r.t to  get_product_list call: 

1) What is the significance of  below parameters.Why they do return as empty?
[IsFeatured] => 
[IsComingSoon] => 

2) Is MAXZOOM indicating that on frontend.Does this mean in CSS i can scale to only 150%
[MaxZoom] => 1.5
zoom:150%

3) Is MAXZOOM indicating that on frontend.Does this mean in CSS i can scale to only 150%

4) How is [PriceInfo] different from [RetailPrice] object?

5) For [info] array element [0] does not have a key .Is it a bug?

```
                [Info] => Array
                    (
                        [0] => stdClass Object
                            (
                                [Content] => Array
                                    (
                                        [0] => Are you looking for an imaginative way to display a beautiful image without putting holes in the wall or buying additional hardware? These long-lasting, sturdy acrylic blocks can stand up anywhere; no wall required.  In addition, the 3D aspect ads artistic, visual interest to any room. Make your most treasured moments timeless.
                                    )

                                [ContentType] => Text
                                [Index] => 3
                            )

                        [1] => stdClass Object
                            (
                                [Content] => Array
                                    (
                                        [0] => 4x6", 5x5", 5x7", 6x6", 8x8"
                                    )

                                [ContentType] => List
                                [Key] => Sizes
                                [Index] => 4
                            )
```

**Comment by micahasmith** [comment]
- `IsFeatured` is if the product is in your list of "featured products"
- `IsComingSoon` is if the product is coming soon, ie unorderable
-  Ignore `MaxZoom`
- `RetailPrice` is what others offer the price at, `PriceInfo` is the actual price
- there are two types of content in the info array-- text and key/value list items. Text items do not have a key, key/value list items do.
