### ISSUE TITLE
Staging recipe id is not working.

### ISSUE THREAD

**Issue by seanwooj** [printdotio/printio-api#25]
I'm not sure if this is the right means of communication, but not sure where else to put it.

I am working on integrating the API into my ruby application am building a small ruby library to act as a wrapper.

In testing the features, I'd like to use my staging recipe id to test so I don't push out any real orders, but my staging id isn't working. My production id is working just fine. 

Is there a staging endpoint, or is my staging recipe ID not yet activated?

Thanks a bunch.

Staging Recipe ID: 97f6a3a1-7bff-4f98-919f-e1a21b50d4ea (not too concerned with others else seeing my staging id)
Partner Name: QuoteNote

**Comment by bhox** [comment]
Hey @seanwooj ,
Your  recipeid looks right, can you confirm that you're using the staging endpoint: http://staging.api.print.io/

Best,
Ben

**Comment by AustenB** [comment]
Sean,

Make sure you also use your Staging API key for your Billing ID.

Its at the bottom of the order post.

Best,

Austen

On Mon, Apr 20, 2015 at 4:03 PM, Ben Hoxie notifications@github.com wrote:

> Hey @seanwooj https://github.com/seanwooj ,
> Your recipeid looks right, can you confirm that you're using the staging
> endpoint: http://staging.api.print.io/
> 
> Best,
> Ben
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/25#issuecomment-94554612
> .

## 

Austen Bernstein
Founder & CEO
printio

**Comment by seanwooj** [comment]
Ah great, thanks. I didn't know if there was a staging API endpoint.

Much appreciated!

Sean

**Comment by bhox** [comment]
Ping us again if you have any other questions! Closing for now
