### ISSUE TITLE
Supplying API key

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#3]
How do I supply the API key for REST requests? I get a 403 error when making calls without the API key.

Also my staging recipe ID does not work on the staging endpoint, but my production recipe ID does work on the staging endpoint.

**Comment by AustenB** [comment]
What is your account name.

I will look to see what was incorrectly told to you.

Who is your account rep?

**Comment by chrischen** [comment]
My account should be under this email: chris.chen21@gmail.com mailto:chris.chen21@gmail.com.

**Comment by chrischen** [comment]
Also I edited the question. I meant to ask how to supply the API key in the REST request.

**Comment by micahasmith** [comment]
use the `recipeId` querystring like `?recipeId=00000000-1234-1234-123456789012`
