### ISSUE TITLE
Problem submitting to /orders

### ISSUE THREAD

**Issue by pierre-dubuisson** [printdotio/printio-api#39]
Trying to test the /orders POST in the staging environment, but I'm getting numerous errors in return.  Here is my error reference:  4e2e6bf0-32c0-4ba4-af54-0f660ac27fe1

It seems like the errors are implying that I'm supposed to provide payment information, but I was under the impression that we'd be submitting these orders as a partner which would allow us to complete payments at a later stage.  Please advise.

**Comment by micahasmith** [comment]
closing since we fixed via email
