### ISSUE TITLE
Image requirements

### ISSUE THREAD

**Issue by chrischen** [printdotio/printio-api#4]
If I submit a landscape image of width: 20 inches, height: 10 inches for the CanvsWrp-BlkWrp-10x20, will the image be rotated to align with the 10x20 dimension, or do I have to rotate the image to width 10 inches, height 20 inches before submitting?

**Comment by AustenB** [comment]
For Canvas Wraps. If you submit it with the image oriented so the top is on the left. It will arrive with a hook to hang on it from either the left side or the top so it will solve this issue for you. @chrischen

**Comment by chrischen** [comment]
I placed two orders with the top on the right. Can I cancel them? How do I
specify if the hook is on the left or the top?

**Comment by AustenB** [comment]
It arrives with two hooks. Please contact partner/customer support about
canceling orders.

On Sat, Feb 28, 2015 at 1:26 PM, chrischen notifications@github.com wrote:

> I placed two orders with the top on the right. Can I cancel them? How do I
> specify if the hook is on the left or the top?
> 
> On Sat, Feb 28, 2015, 10:24 AM Austen Bernstein notifications@github.com
> wrote:
> 
> > For Canvas Wraps. If you submit it with the image oriented so the top is
> > on the left. It will arrive with a hook to hang on it from either the
> > left
> > side or the top so it will solve this issue for you. @chrischen
> > https://github.com/chrischen
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/printdotio/printio-api/issues/4#issuecomment-76538508>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/printio-api/issues/4#issuecomment-76538612
> .

## 

Austen Bernstein
Founder & CEO
printio
