### ISSUE TITLE
Country Code for Product Variants?

### ISSUE THREAD

**Issue by terhechte** [printdotio/printio-api#5]
Hey, the Schema for the `/productvariants` call lists the data type of `countryCode` as `int`. Is that correct? If yes, how do I find out which country is mapped to which integer? I would have supposed that the value is a two or 4 char language code (i.e. "de" or "de_DE").

**Comment by micahasmith** [comment]
not correct. use strings like "US" or "DE".

will fix. thanks!

**Comment by terhechte** [comment]
Thanks
