### ISSUE TITLE
Stark differences between Swagger Schema and Server Responses: "/productvariants"

### ISSUE THREAD

**Issue by terhechte** [printdotio/printio-api#6]
Hey, I'm currently implementing the API for a Mac OS X app, and started by auto-generating code with swagger-codegen based on the current /api docs. Apart from the fact that the generated code needed a lot of customization to actually compile (I didn't created tickets for this yet, as it is in part a Swagger-Codegen problem, too; I remember that I've had similar issues with objc generation in previous projects that used Swagger APIs), there seem to be quite some differences between server responses and Swagger schema. If its ok, I'll just create tickets whenever I stumble upon such differences.

/productvariants list the following attributes for "ProductOption":
`class ProductOption(OptionId: string, ValueId: string, Name: string, Value: string, IconUrl: string, IconType: string, ColorRgba: string)`

However, the server reply dictionary for a product option object is as follows:

 `{
          "OptionId": "c02deea045fb4d47873985b333db9321",
          "ValueId": "284ec9da7e66449a859ac08bb9ce51b7",
          "Name": "Print Type",
          "Value": "Gloss",
          "ImageUrl": "http://app-imgs.print.io/product-framedprints/glossprint.png",
          "ImageType": "WebImg",
          "SortValue": "1"
        },`

IconType != ImageType, IconUrl != ImageUrl, ColorRgba doesn't appear, and SortValue is unlisted.

Cheers,
Benedikt

**Comment by micahasmith** [comment]
will take a look. thx--

**Comment by terhechte** [comment]
There's another new field on ProductOption which I forgot about: `CmValue`. 

Thanks!

**Comment by micahasmith** [comment]
i've started going through all of the endpoints' models, will try to get all updated everywhere

**Comment by terhechte** [comment]
Awesome, thanks.

**Comment by micahasmith** [comment]
@terhechte all updated. let me know any further issues
